### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by tbodt** [coffeebreakerz/CheekiJailbreeki#1]

**Comment by coffeebreakerz** [comment]
Well, that's correct. You are free to do with it whatever you want

**Comment by tbodt** [comment]
If a project has no license, that means nobody can do anything without permission. Consider adding MIT or Unlicense or WTFPL or something.

**Comment by coffeebreakerz** [comment]
I'll resolve this issue. Thanks for explaining this to me I was not aware of that. The code will be licensed under the WTFPL license from now on.
