### ISSUE TITLE
Followed all of the compilation instructions but "open ./nsxpc2pc.xcodeproj" didn't work

### ISSUE THREAD

**Issue by Cloudftw** [coffeebreakerz/CheekiJailbreeki#11]

**Comment by tbodt** [comment]
do you have xcode installed?

**Comment by Cloudftw** [comment]
all i got installed is xcode command prompt tools i didn't bother with the install time for xcode itself

**Comment by stek29** [comment]
Then get full Xcode installation

**Comment by jakeajames** [comment]
Installing full Xcode is required

**Comment by tbodt** [comment]
you need xcode
