### ISSUE TITLE
Could this be used to execute a nonce generator?

### ISSUE THREAD

**Issue by TheForgottenKing** [coffeebreakerz/CheekiJailbreeki#16]
On 10.3 we do not have a KPP bypass, but we could quickly set the nonce and reboot into DFU, thus allowing an IPSW+SHSH2 downgrade

Stay Cheeki Breeki, Comrade

**Comment by jakeajames** [comment]
You don't need a KPP bypass to set a nonce, just tfp0, so yeah it's possible

**Comment by coffeebreakerz** [comment]
It's possible.

**Comment by TheForgottenKing** [comment]
Will you include this?

**Comment by akasarx** [comment]
Yeah if you submit a pull request with the required code ;)

**Comment by gamla11** [comment]
From What I heard phoenixnonce could be used as a template for this.

**Comment by jakeajames** [comment]
@gamla11 yep

**Comment by LuckyAquatics** [comment]
So how is ios 10.2.1 jailbreak going so far and how long until it should be complete

**Comment by Samgisaninja** [comment]
@LuckyAquatics no eta

**Comment by AeroPwn** [comment]
you'll need to work on it yourself but for the time being i dont think @coffeebreakerz will be working on it sadly. If you'd like to try i'd be happy to help.
