### ISSUE TITLE
Can't cheekibreak on ios 10.3.1

### ISSUE THREAD

**Issue by Kepa2012** [coffeebreakerz/CheekiJailbreeki#18]
Hi i updated offsets for 10.3.1 compiled file and getting ok screen(DAVAY DAVAY Everything is cheeki breeki) but device isnt jailbroken
in xcode debug i see:
failed to get the new target's task port
The debugserver and the katusha (ziVA) are happy to be working for Mr. Trotsky now.
how to fix this?

**Comment by coffeebreakerz** [comment]
Read the documentation of triple_fetch_sdk.
That will explain why you get this error and how you can fix it.
