### ISSUE TITLE
[Question Not an error]  Run in unactived device 

### ISSUE THREAD

**Issue by genhack** [coffeebreakerz/CheekiJailbreeki#21]
Sorry if write here i need support to start this in device not actived yet, i have 3 device and i wont run the project before activation. My question is, Can be possible? , i know springborad disabled all services before the activation but i think there is a ways to do it by lockdown. Thanks for your great job! the test devices are ios 10.3.1 iphone 6.

**Comment by stek29** [comment]
No, there's no way. 
Stealing iPhones is bad.

**Comment by jakeajames** [comment]
@stek29 Not necessarily he stole it, could have been a scam as well, but you're right, no way to bypass ¯\_(ツ)_/¯

**Comment by genhack** [comment]
No its not for bypass, i need it for run some code inside the xmlui ...

**Comment by jigsaw294** [comment]
It's odd that you want to run the code in an inactivated device. What are you tying to accomplish?

**Comment by coffeebreakerz** [comment]
I leave this over to the ingenious person who possesses this beautiful locked assumably stolen or 'fairly' found device. All I can say there is that you'll never be able to run code on the device in normal mode while the device is unactivated. I suggest studying Apple's private activation servers but ofcourse you will need AppleConnect and access to Apple's VPN for that and you need to be an official Apple Employee and you should discuss this with your superior first
