### ISSUE TITLE
 Could not compile

### ISSUE THREAD

**Issue by Cloudftw** [coffeebreakerz/CheekiJailbreeki#23]
I do not know where to save the logs for xcode so i cannot upload any logs

**Comment by jigsaw294** [comment]
then what was the purpose of this issue? lol it doesn't help the developer to fix anything.

**Comment by Cloudftw** [comment]
Implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int')
