### ISSUE TITLE
Could not compile

### ISSUE THREAD

**Issue by Cloudftw** [coffeebreakerz/CheekiJailbreeki#24]
Implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int')

**Comment by stek29** [comment]
Why are you even trying if you don't know what is that warning caused by usually and don't know how to fix it?
Also, it's almost always warning and not a error, unless Cheeki has some very strict flags and I highly doubt it does.

**Comment by coffeebreakerz** [comment]
Cloudftw, that's a warning. One that warns for a possible type confusion / precision bug.
Warnings are yellow, errors are red. My code avoids them as else I'd be mad.
