### ISSUE TITLE
Can't compile because not on mac

### ISSUE THREAD

**Issue by Cloudftw** [coffeebreakerz/CheekiJailbreeki#9]

**Comment by stek29** [comment]
https://lmgtfy.com/?q=macos+virtual+machine

**Comment by coffeebreakerz** [comment]
Here: I created a tutorial of setting up a VM.
It includes VMWare Workstation Pro licenses. Used = Used.
https://github.com/MTJailed/macOS-Sierra-VM

**Comment by Cloudftw** [comment]
i have now setup a virtual machine didn't see this before
